alter table if exists public."Customer" rename to customer;

create table if not exists public.customer (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  vehicle_type text,
  tyre_size text,
  service text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.customer
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists vehicle_type text,
  add column if not exists tyre_size text,
  add column if not exists service text,
  add column if not exists message text,
  add column if not exists created_at timestamptz not null default now();

alter table public.customer enable row level security;

grant usage on schema public to anon;
grant insert on public.customer to anon;

drop policy if exists "Allow enquiry inserts" on public.customer;

create policy "Allow enquiry inserts"
  on public.customer
  for insert
  to anon
  with check (true);

notify pgrst, 'reload schema';
